<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Mapper\Api\Representation\MapperRepresentation[] $mappings
 * @var \Mapper\Api\Representation\MapperRepresentation[] $resources
 * @var array $internalMappings
 */

$plugins = $this->getHelperPluginManager();
$i18n = $plugins->get('i18n');
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$urlHelper = $plugins->get('url');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$this->headLink()
    ->appendStylesheet($assetUrl('css/mapper.css', 'Mapper'));

$this->htmlElement('body')->appendAttribute('class', 'mapper browse');

$userIsAllowedCreate = $this->userIsAllowed(\Mapper\Api\Adapter\MapperAdapter::class, 'create');
?>

<?= $this->pageTitle($translate('Mappings'), 1, $translate('Mapper')) ?>

<div id="page-actions">
    <?php if ($userIsAllowedCreate): ?>
    <?= $hyperlink($translate('Add new mapping'), $urlHelper('admin/mapper/default', ['action' => 'add'], true), ['class' => 'button']) ?>
    <?php endif; ?>
</div>

<h2><?= $escape($translate('Configuration of mappings')) ?></h2>

<h3><?= $escape($translate('Configured mappings')) ?></h3>
<?php if (count($mappings)): ?>
<table class="tablesaw batch-edit" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?= $escape($translate('Name')) ?></th>
            <th><?= $escape($translate('Last modified')) ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($mappings as $mapping): ?>
        <?php $userIsAllowedUpdate = $mapping->userIsAllowed('update'); ?>
        <?php $userIsAllowedDelete = $mapping->userIsAllowed('delete'); ?>
        <tr>
            <td>
                <?= $mapping->link($mapping->label(), 'show') ?>
                <ul class="actions">
                    <?php if ($userIsAllowedUpdate): ?>
                    <li><?= $mapping->link('', 'edit', [
                        'class' => 'o-icon-edit',
                        'title' => $translate('Edit'),
                    ]) ?></li>
                    <?php endif; ?>
                    <?php if ($userIsAllowedCreate): ?>
                    <li><?= $mapping->link('', 'copy', [
                        'class' => 'o-icon- fa-solid fa-copy',
                        'title' => $translate('Copy'),
                    ]) ?></li>
                    <?php endif; ?>
                    <?php if ($userIsAllowedDelete): ?>
                    <li><?= $mapping->link('', 'delete', [
                        'class' => 'o-icon-delete',
                        'title' => $translate('Delete'),
                    ]) /*
                    echo $this->hyperlink('', '#', [
                        'data-sidebar-selector' => '#sidebar',
                        'data-sidebar-content-url' => $importer->url('delete-confirm'),
                        'class' => 'o-icon-delete sidebar-content',
                        'title' => $translate('Delete'),
                    ]) */ ?></li>
                    <?php endif; ?>
                </ul>
            </td>
            <td>
                <?= $i18n->dateFormat($mapping->modified() ?: $mapping->created(), 'medium', 'short') ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
<div class="no-resources">
    <p><?= $escape($translate('No configured mappings yet.')) ?></p>
</div>
<?php endif; ?>

<?php if (!empty($internalMappings)): ?>
<h3><?= $escape($translate('Internal mappings (files on server, to be copied)')) ?></h3>
<table class="tablesaw batch-edit" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?= $escape($translate('Name')) ?></th>
            <th><?= $escape($translate('Source')) ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($internalMappings as $id => $name): ?>
        <tr>
            <td>
                <a href="<?= $escapeAttr($urlHelper('admin/mapper/default', ['action' => 'show'], ['query' => ['id' => $id]])) ?>"><?= $escape($name) ?></a>
                <ul class="actions">
                    <?php if ($userIsAllowedCreate): ?>
                    <li><a class="o-icon- fa-solid fa-copy" title="<?= $escapeAttr($translate('Copy as new mapping')) ?>" href="<?= $escapeAttr($urlHelper('admin/mapper/default', ['action' => 'copy'], ['query' => ['id' => $id]])) ?>"></a></li>
                    <?php endif; ?>
                </ul>
            </td>
            <td>
                <?= $escape(strtok(mb_substr($id, 7), '/')) ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>
